### ISSUE TITLE
Built component crashes 4D

### ISSUE THREAD

**Issue by elutz** [vdelachaux/4DPop-QuickOpen#3]
When I build the component on my own and run it with 4D 20R5, 4D crashes when I try to open one of the found methods in QuickOpen.
It crashes at this line in the `design.edit()` function.
``` 
Try(METHOD OPEN PATH(This.paths.query("type = :1"; $designObject.type).pop().path+$designObject.name; *))
```
If I remove the `Try` command and add an error handler around the code, it no longer crashes.

This is with 4D 20R5 Build 100217 on Windows 10.

**Comment by vdelachaux** [comment]
Thanks for the report, I'll look into it soon.

**Comment by vdelachaux** [comment]
Hi Lutz
I've reproduced the crash you reported when the component is compiled with 20R5.
It's probably a bug in the 4D compiler which has since been corrected since the problem no longer occurs with 20R6, 20R7 (soon available) and our development branch.
As the 20R5 is no longer maintained, I suggest changing to the 20R6+.

Question: Why do you need to compil this component? Have you made any changes that would be beneficial to everyone? 
If so, please let us know.

Regards
Vincent

**Comment by elutz** [comment]
I had the crashing problem even with the built component and want to get a working solution because I use the component quite often. So I decided to take a look at the code.

We will wait for the 20R6 to be officially released.

Thanks!

**Comment by vdelachaux** [comment]
in a very short time
Vincent
